name: check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: run eslint
        run: |
          npm ci
          npm run typecheck
          npm run lint:check
          npm run format:check
        env:
          CI: true
