name: publish
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'tsconfig.build.json'
      - 'src/*'

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: 'pg-error-enum'
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true

  publish:
    if: ${{ needs.release.outputs.release_created }}
    needs: [release]
    runs-on: ubuntu-latest
    environment:
      name: NPM
      url: https://www.npmjs.com/package/pg-error-enum/v/${{ needs.release.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public
