name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps, build, then clear deps
        run: |
          npm ci
          npm run build
          rm -rf node_modules
      # Not using a matrix here since it's simpler
      # to just duplicate it and not spawn new instances
      - name: Test on Node 16
        run: |
          node -v
          npm run test
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Test on Node 14
        run: |
          node -v
          npm run test
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Test on Node 12
        run: |
          node -v
          npm run test
