name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps, build, then clear deps
        run: |
          npm ci
          npm run build
          rm -rf node_modules
      - name: Test on Node 20
        run: |
          node -v
          npm run test
      # Not using a matrix here since it's simpler
      # to just duplicate it and not spawn new instances
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Test on Node 18
        run: |
          node -v
          npm run test
