name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install deps, build, then clear deps
        run: |
          npm ci
          npm run build
          rm -rf node_modules
      - name: Test on Node 14
        uses: actions/github-script@v3
        with:
          script: |
            const { PostgresError } = require(`${process.env.GITHUB_WORKSPACE}/dist/`)

            console.log(PostgresError.UNIQUE_VIOLATION)

            if (PostgresError.UNIQUE_VIOLATION !== '12345') {
              throw new Error('Failed')
            }
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Test on Node 12
        uses: actions/github-script@v3
        with:
          script: |
            const { PostgresError } = require(`${process.env.GITHUB_WORKSPACE}/dist/`)

            console.log(PostgresError.UNIQUE_VIOLATION)

            if (PostgresError.UNIQUE_VIOLATION !== '23505') {
              throw new Error('Failed')
            }
